# See the project's README about setting DATAFOLDER and ETCFOLDER.

version: "3.8"

services:
  clamav:
    image: "mkodockx/docker-clamav"
    container_name: "clamav"
    volumes:
        - "${DATAFOLDER}:/data"
        - "${ETCFOLDER}:/data/etc"
    expose :
        - "3310"        
    networks :
        - preingest-network        
  xslweb:
    image: "noordhollandsarchief/xslweb:development"
    container_name: "xslweb"
    volumes:
        - "${DATAFOLDER}:/data"
        - "${ETCFOLDER}:/data/etc"
    expose:
        - "8080" 
    environment:
        - "PREINGEST_WEBAPI=http://Noord.HollandsArchief.Pre.Ingest.WebApi"
    ports:
        - "8888:8080"     
    networks :
        - preingest-network
  droid:
    image: "noordhollandsarchief/droidvalidationwebapi:development"
    container_name: "droid"
    volumes:
        - "${DATAFOLDER}:/data" 
        - "${ETCFOLDER}:/data/etc"
    expose:
        - "8080"
    environment:
        - "PREINGEST_WEBAPI=http://Noord.HollandsArchief.Pre.Ingest.WebApi"        
    networks :
        - preingest-network        
  preingest:
    image: "nhapreingest/noordhollandsarchiefpreingestwebapi:development"
    container_name: "Noord.HollandsArchief.Pre.Ingest.WebApi"
    volumes:
        - "${DATAFOLDER}:/data"  
        - "${ETCFOLDER}:/data/etc"
    expose:
        - "80"
    # Only (temporarily) mapped here for direct debugging access to the API's HTTP endpoints
    ports:
      - "8000:80"
    networks :
        - preingest-network          
    depends_on:
      - droid
      - clamav
      - xslweb 
  frontend:
    image: "noordhollandsarchief/preingest-frontend:development"
    container_name: "preingest-frontend"
    expose:
      - "80"
    ports:
      - "9000:80"
    environment:
      - "PROXY_API_DEST=http://Noord.HollandsArchief.Pre.Ingest.WebApi/api/"
    networks:
      - preingest-network
    depends_on:
      - preingest
networks:
    preingest-network:
        driver: bridge
