# See the project's README about setting DATAFOLDER, SIPCREATORFOLDER and TOMCATLOGFOLDER.

version: "3.8"

services:
  clamav:
    image: "mkodockx/docker-clamav"
    container_name: "clamav"
    volumes:
        - "${DATAFOLDER}:/data"
    expose :
        - "3310"        
    networks :
        - preingest-network        
  xslweb:
    image: "noordhollandsarchief/xslweb:development"
    container_name: "xslweb"
    volumes:
        - "${DATAFOLDER}:/data"
        - "${SIPCREATORFOLDER}:/nha/SIP_Creator"
        - "${TOMCATLOGFOLDER}:/nha/tomcat-logs"
    expose:
        - "8080" 
    environment:
        - "PREINGEST_WEBAPI=http://Noord.HollandsArchief.Pre.Ingest.WebApi"
    ports:
        - "8888:8080"     
    networks :
        - preingest-network
  droid:
    image: "noordhollandsarchief/droidvalidationwebapi:development"
    container_name: "droid"
    volumes:
        - "${DATAFOLDER}:/data"
    expose:
        - "8080"
    environment:
        - "PREINGEST_WEBAPI=http://Noord.HollandsArchief.Pre.Ingest.WebApi"        
    networks :
        - preingest-network        
  preingest:
    image: "nhapreingest/noordhollandsarchiefpreingestwebapi:development"
    container_name: "Noord.HollandsArchief.Pre.Ingest.WebApi"
    volumes:
        - "${DATAFOLDER}:/data"
        - "${TRANSFERAGENTTESTFOLDER}:/tatf"
        - "${TRANSFERAGENTPRODFOLDER}:/tapf"
    expose:
        - "80"
    # Only (temporarily) mapped here for direct debugging access to the API's HTTP endpoints
    ports:
      - "8000:80"
    environment:
      - AppSettings:DataFolderName=/data
      - AppSettings:ClamServerPort=3310
      - AppSettings:ClamServerNameOrIp=clamav
      - AppSettings:XslWebServerName=xslweb
      - AppSettings:XslWebServerPort=8080
      - AppSettings:DroidServerName=droid
      - AppSettings:DroidServerPort=8080
    networks:
      - preingest-network
    depends_on:
      - droid
      - clamav
      - xslweb
  workerservice:
    image: "nhapreingest/noordhollandsarchiefpreingestworkerservice:development"
    container_name: "Noord.HollandsArchief.Pre.Ingest.WorkerService"
    environment:
      - AppSettings:EventHubUrl=http://Noord.HollandsArchief.Pre.Ingest.WebApi/preingestEventHub/
      - AppSettings:WebApiUrl=http://Noord.HollandsArchief.Pre.Ingest.WebApi/
    networks:
      - preingest-network
    depends_on:
      - preingest    
  frontend:
    image: "noordhollandsarchief/preingest-frontend:development"
    container_name: "preingest-frontend"
    expose:
      - "80"
    ports:
      - "9000:80"
    environment:
      - "PROXY_API_DEST=http://Noord.HollandsArchief.Pre.Ingest.WebApi/api/"
      - "PROXY_EVENTHUB_DEST=http://Noord.HollandsArchief.Pre.Ingest.WebApi/preingestEventHub/"
    networks:
      - preingest-network
    depends_on:
      - workerservice
networks:
    preingest-network:
        driver: bridge
