//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Noord.HollandsArchief.Pre.Ingest.WebTool.Entities.Droid
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationalarchives.gov.uk/CollectionProfile")]
    [System.Xml.Serialization.XmlRootAttribute("FileProfile", Namespace="http://www.nationalarchives.gov.uk/CollectionProfile", IsNullable=false)]
    public partial class FileProfileType {
        
        private System.DateTime profilingStartDateField;
        
        private System.DateTime profilingEndDateField;
        
        private System.DateTime profilingSaveDateField;
        
        private string totalReadableFilesField;
        
        private string totalUnreadableFilesField;
        
        private string totalUnreadableFoldersField;
        
        private decimal totalSizeField;
        
        private decimal smallestSizeField;
        
        private decimal largestSizeField;
        
        private decimal meanSizeField;
        
        private string[] pathsProcessedField;
        
        private YearItemType[] byYearField;
        
        private FormatItemType[] byFormatField;
        
        /// <remarks/>
        public System.DateTime profilingStartDate {
            get {
                return this.profilingStartDateField;
            }
            set {
                this.profilingStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime profilingEndDate {
            get {
                return this.profilingEndDateField;
            }
            set {
                this.profilingEndDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime profilingSaveDate {
            get {
                return this.profilingSaveDateField;
            }
            set {
                this.profilingSaveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string totalReadableFiles {
            get {
                return this.totalReadableFilesField;
            }
            set {
                this.totalReadableFilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string totalUnreadableFiles {
            get {
                return this.totalUnreadableFilesField;
            }
            set {
                this.totalUnreadableFilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string totalUnreadableFolders {
            get {
                return this.totalUnreadableFoldersField;
            }
            set {
                this.totalUnreadableFoldersField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalSize {
            get {
                return this.totalSizeField;
            }
            set {
                this.totalSizeField = value;
            }
        }
        
        /// <remarks/>
        public decimal smallestSize {
            get {
                return this.smallestSizeField;
            }
            set {
                this.smallestSizeField = value;
            }
        }
        
        /// <remarks/>
        public decimal largestSize {
            get {
                return this.largestSizeField;
            }
            set {
                this.largestSizeField = value;
            }
        }
        
        /// <remarks/>
        public decimal meanSize {
            get {
                return this.meanSizeField;
            }
            set {
                this.meanSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("pathItem", IsNullable=false)]
        public string[] pathsProcessed {
            get {
                return this.pathsProcessedField;
            }
            set {
                this.pathsProcessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("yearItem", IsNullable=false)]
        public YearItemType[] byYear {
            get {
                return this.byYearField;
            }
            set {
                this.byYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("formatItem", IsNullable=false)]
        public FormatItemType[] byFormat {
            get {
                return this.byFormatField;
            }
            set {
                this.byFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationalarchives.gov.uk/CollectionProfile")]
    public partial class YearItemType {
        
        private string yearField;
        
        private string numFilesField;
        
        private decimal totalFileSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numFiles {
            get {
                return this.numFilesField;
            }
            set {
                this.numFilesField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalFileSize {
            get {
                return this.totalFileSizeField;
            }
            set {
                this.totalFileSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationalarchives.gov.uk/CollectionProfile")]
    public partial class FormatItemType {
        
        private string pUIDField;
        
        private string mIMEField;
        
        private string formatNameField;
        
        private string formatVersionField;
        
        private string numFilesField;
        
        private decimal totalFileSizeField;
        
        /// <remarks/>
        public string PUID {
            get {
                return this.pUIDField;
            }
            set {
                this.pUIDField = value;
            }
        }
        
        /// <remarks/>
        public string MIME {
            get {
                return this.mIMEField;
            }
            set {
                this.mIMEField = value;
            }
        }
        
        /// <remarks/>
        public string FormatName {
            get {
                return this.formatNameField;
            }
            set {
                this.formatNameField = value;
            }
        }
        
        /// <remarks/>
        public string FormatVersion {
            get {
                return this.formatVersionField;
            }
            set {
                this.formatVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numFiles {
            get {
                return this.numFilesField;
            }
            set {
                this.numFilesField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalFileSize {
            get {
                return this.totalFileSizeField;
            }
            set {
                this.totalFileSizeField = value;
            }
        }
    }
}
