# See the project's README about setting DATAFOLDER and ETCFOLDER.
version: '3.0'
services:
    xslweb:
        image: "pmasereeuwnha/xslwebfrontend"
        container_name: "xslwebfrontend"
        ports:
            - "8888:8080"
        volumes:
            - "${DATAFOLDER}:/data"
            - "${ETCFOLDER}:/data/etc"