# Define the environment variable DATAFOLDER for the correct expandion of ${DATAFOLDER} below.
# E.g.:
# export DATAFOLDER=/home/pieter/noord-hollandsarchief/data
# set DATAFOLDER=D:\data

version: '3.0'
services:
    xslweb:
        image: "pmasereeuwnha/xslweb"
        container_name: "xslweb-jdk8"
        ports:
            - "8080:8080"
        volumes:
            - "${DATAFOLDER}:/data"